name: CI

on:
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - name: Git checkout
        uses: actions/checkout@v2.0.0
      
      - name: Start redis server
        uses: supercharge/redis-github-action@1.1.0
        
      - name: Build and test
        env:
          APP_ENV: testing
          DISCORD_TRYBOT_TOKEN: ${{ secrets.DISCORD_TRYBOT_TOKEN }}
          REDDIT_RSS_FEED_TOKEN: ${{ secrets.REDDIT_RSS_FEED_TOKEN }}
          REDDIT_RSS_FEED_USER: ${{ secrets.REDDIT_RSS_FEED_USER }}
        run: |
          cp .env.example .env
          composer install
          php artisan key:generate
          ./vendor/phpunit/phpunit/phpunit
        
